# Auto-generated by GridEditor — do not edit by hand unless you know what you're doing.
from math import sqrt, sin, cos, tan, asin, acos, atan, atan2, sinh, cosh, tanh, log, log10, exp, floor, ceil, fabs, pi, e, tau

def sgn(v):
    return (v > 0) - (v < 0)

def clamp(v, lo, hi):
    return lo if v < lo else (hi if v > hi else v)

def grid_value(x, y, o, h, w, cx, cy):
    # coordinates relative to center (match visualizer)
    x = x - cx
    y = y - cy

    # fields evaluated in dependency order
    sy = y % h
    ny = (-y) % h
    wx = (-x) % w
    idxS = 3
    idxW = 2
    idxN = 1
    idxE = 0
    ex = x % w
    tS = min((o-idxS)%4, (idxS-o)%4)
    tW = min((o-idxW)%4, (idxW-o)%4)
    tN = min((o-idxN)%4, (idxN-o)%4)
    tE = min((o-idxE)%4, (idxE-o)%4)

    return float(min( tE + ex + (0 if (min(ny,sy)==0) else 1 + min(ny,sy)),  tW + wx + (0 if (min(ny,sy)==0) else 1 + min(ny,sy)),  tN + ny + (0 if (min(ex,wx)==0) else 1 + min(ex,wx)),  tS + sy + (0 if (min(ex,wx)==0) else 1 + min(ex,wx)) ))
